name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --workspace --exclude pwnd_browser --verbose
    - name: Run tests
      run: cargo test --verbose
  wasm:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build
        run: cargo build --package pwnd_browser --target wasm32-unknown-unknown --verbose
