name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --workspace --exclude pwnd_browser
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
  wasm:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --package pwnd_browser
