name: rust

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release -Z unstable-options --out-dir build --workspace
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --workspace
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: pwnd_${{ matrix.os }}
        path: build
  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Ensure wasm32 target
        run: rustup target add wasm32-unknown-unknown
      - name: Install & build
        run: |
          cd browser
          npm ci
          npm run prepare
      - name: Upload web artifacts
        uses: actions/upload-artifact@v1
        with:
          name: pwnd_browser
          path: browser/dist
